# Generated by Django 3.2.12 on 2022-02-28 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import leaveapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full names')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=250)),
            ],
            bases=(leaveapp.models.ModelMethods, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Leave')),
                ('description', models.TextField(blank=True)),
            ],
            bases=(leaveapp.models.ModelMethods, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100, verbose_name='Role')),
                ('role_description', models.TextField(blank=True)),
            ],
            bases=(leaveapp.models.ModelMethods, models.Model),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('requested_days', models.IntegerField(blank=True, default=1)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.employee')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.leavetype')),
            ],
            bases=(leaveapp.models.ModelMethods, models.Model),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.role'),
        ),
    ]
